import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";


const YashPopins = Poppins({
  variable: "--font-YashPopins",
  subsets: ['latin'],
  weight: ['300','400','500','600','700']
})

export const YashMonSerat = Montserrat({
  variable: "--font-YashMonSerat",
  subsets: ['latin'],
  weight: ['300','400','500','600','700']
})

export const metadata = {
  title: "Dragon news portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${YashPopins.className} min-h-full flex flex-col`}>
        {children}
        </body>
    </html>
  );
}
